### ISSUE TITLE
catch() as function

### ISSUE THREAD

**Issue by fastner** [sebastian-software/jasy#16]
In new Promises spec in ES6 there is a catch() function. Using this results in 

    jasy.script.tokenize.Tokenizer.ParseError: Syntax error: Missing identifier

**Comment by fastner** [comment]
example code:

    var p = new core.event.Promise(function(resolve,reject){});
    p.then(function() {}).catch(function() {});

**Comment by swernerx** [comment]
Thanks for reporting. Should be better with 87ce1dc - We might have more stuff to rework for full ES6 support though.
